[versions]
kotlin = "2.1.10"
exposed = "0.60.0"
ksp = "2.1.10-1.0.31"


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.14.1" }
kotlinpoet-interop = { module = "com.squareup:kotlinpoet-ksp", version = "1.14.1" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }

